apiVersion: apps/v1
kind: Deployment
metadata:
  name: bdd
spec:
  selector:
    matchLabels:
      app: bdd
  template:
    metadata:
      labels:
        app: bdd
    spec:
      containers:
      - name: bdd
        image: mohamedakka21/ilkiformation:bdd
        ports:
        - containerPort: 3306
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "P@ssw0rd"
